name: dominican_casino
description: "Dominican Card Game"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.12.0-46.0.dev

dependencies:
  cloud_firestore: ^6.1.2
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  go_router: ^17.1.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  uuid: ^4.5.3
  cupertino_icons: ^1.0.0
  dotted_border: ^2.1.0
  app_links: ^6.0.0
  share_plus: ^12.0.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/logo_icon_wooden_transparent.png"
