// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw5UbfG5zMd3PpKIACJ7OfEvxeclLHLn0',
    appId: '1:932020449632:web:7e9af9ddd03e2c60c9ee05',
    messagingSenderId: '932020449632',
    projectId: 'dominican-casino',
    authDomain: 'dominican-casino.firebaseapp.com',
    storageBucket: 'dominican-casino.firebasestorage.app',
    measurementId: 'G-WRB5LNKS9F',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYylFD_Vl8q60bRPO_6r0vAjX_EV02w8g',
    appId: '1:932020449632:ios:316853b7dc8a39fdc9ee05',
    messagingSenderId: '932020449632',
    projectId: 'dominican-casino',
    storageBucket: 'dominican-casino.firebasestorage.app',
    iosClientId:
        '932020449632-pdpqg0pmdj5mr46of60vcqijitqq45gv.apps.googleusercontent.com',
    iosBundleId: 'com.example.dominicanCasino',
  );
}
