// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Web OAuth client id — required as [GoogleSignIn] `serverClientId` on Android
  /// so Firebase Auth receives an ID token. Also appears in `google-services.json`
  /// as an `oauth_client` entry with `client_type: 3`.
  static const String googleWebClientId =
      '932020449632-la1rnifajdj2jfdo8mrgtbskdpe0iljp.apps.googleusercontent.com';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw5UbfG5zMd3PpKIACJ7OfEvxeclLHLn0',
    appId: '1:932020449632:web:7e9af9ddd03e2c60c9ee05',
    messagingSenderId: '932020449632',
    projectId: 'dominican-casino',
    authDomain: 'dominican-casino.firebaseapp.com',
    storageBucket: 'dominican-casino.firebasestorage.app',
    measurementId: 'G-WRB5LNKS9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkD6O_3RSAs9ZyFWXtQ_283pYSs0aX-ek',
    appId: '1:932020449632:android:6541fabbce84c931c9ee05',
    messagingSenderId: '932020449632',
    projectId: 'dominican-casino',
    storageBucket: 'dominican-casino.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYylFD_Vl8q60bRPO_6r0vAjX_EV02w8g',
    appId: '1:932020449632:ios:93523b9132363a72c9ee05',
    messagingSenderId: '932020449632',
    projectId: 'dominican-casino',
    storageBucket: 'dominican-casino.firebasestorage.app',
    iosClientId:
        '932020449632-hkq967iebi5413bfr275l3es99n03oj8.apps.googleusercontent.com',
    iosBundleId: 'com.sr2.dominicanCasino',
  );
}
